// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: auth/v1/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Recipient:
	//
	//	*LoginRequest_Phone
	//	*LoginRequest_Email
	Recipient     isLoginRequest_Recipient `protobuf_oneof:"recipient"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetRecipient() isLoginRequest_Recipient {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *LoginRequest) GetPhone() string {
	if x != nil {
		if x, ok := x.Recipient.(*LoginRequest_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Recipient.(*LoginRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

type isLoginRequest_Recipient interface {
	isLoginRequest_Recipient()
}

type LoginRequest_Phone struct {
	Phone string `protobuf:"bytes,1,opt,name=phone,proto3,oneof"`
}

type LoginRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*LoginRequest_Phone) isLoginRequest_Recipient() {}

func (*LoginRequest_Email) isLoginRequest_Recipient() {}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

type VerifyOTPRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Recipient:
	//
	//	*VerifyOTPRequest_Phone
	//	*VerifyOTPRequest_Email
	Recipient     isVerifyOTPRequest_Recipient `protobuf_oneof:"recipient"`
	Otp           string                       `protobuf:"bytes,3,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOTPRequest) Reset() {
	*x = VerifyOTPRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOTPRequest) ProtoMessage() {}

func (x *VerifyOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOTPRequest.ProtoReflect.Descriptor instead.
func (*VerifyOTPRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyOTPRequest) GetRecipient() isVerifyOTPRequest_Recipient {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *VerifyOTPRequest) GetPhone() string {
	if x != nil {
		if x, ok := x.Recipient.(*VerifyOTPRequest_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

func (x *VerifyOTPRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Recipient.(*VerifyOTPRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *VerifyOTPRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type isVerifyOTPRequest_Recipient interface {
	isVerifyOTPRequest_Recipient()
}

type VerifyOTPRequest_Phone struct {
	Phone string `protobuf:"bytes,1,opt,name=phone,proto3,oneof"`
}

type VerifyOTPRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*VerifyOTPRequest_Phone) isVerifyOTPRequest_Recipient() {}

func (*VerifyOTPRequest_Email) isVerifyOTPRequest_Recipient() {}

type VerifyOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOTPResponse) Reset() {
	*x = VerifyOTPResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOTPResponse) ProtoMessage() {}

func (x *VerifyOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOTPResponse.ProtoReflect.Descriptor instead.
func (*VerifyOTPResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyOTPResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *VerifyOTPResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RestoreAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Recipient:
	//
	//	*RestoreAccountRequest_Phone
	//	*RestoreAccountRequest_Email
	Recipient     isRestoreAccountRequest_Recipient `protobuf_oneof:"recipient"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreAccountRequest) Reset() {
	*x = RestoreAccountRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreAccountRequest) ProtoMessage() {}

func (x *RestoreAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreAccountRequest.ProtoReflect.Descriptor instead.
func (*RestoreAccountRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RestoreAccountRequest) GetRecipient() isRestoreAccountRequest_Recipient {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *RestoreAccountRequest) GetPhone() string {
	if x != nil {
		if x, ok := x.Recipient.(*RestoreAccountRequest_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

func (x *RestoreAccountRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Recipient.(*RestoreAccountRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

type isRestoreAccountRequest_Recipient interface {
	isRestoreAccountRequest_Recipient()
}

type RestoreAccountRequest_Phone struct {
	Phone string `protobuf:"bytes,1,opt,name=phone,proto3,oneof"`
}

type RestoreAccountRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*RestoreAccountRequest_Phone) isRestoreAccountRequest_Recipient() {}

func (*RestoreAccountRequest_Email) isRestoreAccountRequest_Recipient() {}

type RestoreAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreAccountResponse) Reset() {
	*x = RestoreAccountResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreAccountResponse) ProtoMessage() {}

func (x *RestoreAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreAccountResponse.ProtoReflect.Descriptor instead.
func (*RestoreAccountResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

type DeleteAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Recipient:
	//
	//	*DeleteAccountRequest_Phone
	//	*DeleteAccountRequest_Email
	Recipient     isDeleteAccountRequest_Recipient `protobuf_oneof:"recipient"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAccountRequest) GetRecipient() isDeleteAccountRequest_Recipient {
	if x != nil {
		return x.Recipient
	}
	return nil
}

func (x *DeleteAccountRequest) GetPhone() string {
	if x != nil {
		if x, ok := x.Recipient.(*DeleteAccountRequest_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

func (x *DeleteAccountRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Recipient.(*DeleteAccountRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

type isDeleteAccountRequest_Recipient interface {
	isDeleteAccountRequest_Recipient()
}

type DeleteAccountRequest_Phone struct {
	Phone string `protobuf:"bytes,1,opt,name=phone,proto3,oneof"`
}

type DeleteAccountRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*DeleteAccountRequest_Phone) isDeleteAccountRequest_Recipient() {}

func (*DeleteAccountRequest_Email) isDeleteAccountRequest_Recipient() {}

type DeleteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\aauth.v1\"K\n" +
	"\fLoginRequest\x12\x16\n" +
	"\x05phone\x18\x01 \x01(\tH\x00R\x05phone\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05emailB\v\n" +
	"\trecipient\"\x0f\n" +
	"\rLoginResponse\"a\n" +
	"\x10VerifyOTPRequest\x12\x16\n" +
	"\x05phone\x18\x01 \x01(\tH\x00R\x05phone\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x12\x10\n" +
	"\x03otp\x18\x03 \x01(\tR\x03otpB\v\n" +
	"\trecipient\"[\n" +
	"\x11VerifyOTPResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"T\n" +
	"\x15RestoreAccountRequest\x12\x16\n" +
	"\x05phone\x18\x01 \x01(\tH\x00R\x05phone\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05emailB\v\n" +
	"\trecipient\"\x18\n" +
	"\x16RestoreAccountResponse\"S\n" +
	"\x14DeleteAccountRequest\x12\x16\n" +
	"\x05phone\x18\x01 \x01(\tH\x00R\x05phone\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05emailB\v\n" +
	"\trecipient\"\x17\n" +
	"\x15DeleteAccountResponse\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"^\n" +
	"\x14RefreshTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken2\xf9\x02\n" +
	"\vAuthService\x126\n" +
	"\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x16.auth.v1.LoginResponse\x12B\n" +
	"\tVerifyOTP\x12\x19.auth.v1.VerifyOTPRequest\x1a\x1a.auth.v1.VerifyOTPResponse\x12Q\n" +
	"\x0eRestoreAccount\x12\x1e.auth.v1.RestoreAccountRequest\x1a\x1f.auth.v1.RestoreAccountResponse\x12N\n" +
	"\rDeleteAccount\x12\x1d.auth.v1.DeleteAccountRequest\x1a\x1e.auth.v1.DeleteAccountResponse\x12K\n" +
	"\fRefreshToken\x12\x1c.auth.v1.RefreshTokenRequest\x1a\x1d.auth.v1.RefreshTokenResponseB\x18Z\x16shared/proto/auth;authb\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_auth_v1_auth_proto_goTypes = []any{
	(*LoginRequest)(nil),           // 0: auth.v1.LoginRequest
	(*LoginResponse)(nil),          // 1: auth.v1.LoginResponse
	(*VerifyOTPRequest)(nil),       // 2: auth.v1.VerifyOTPRequest
	(*VerifyOTPResponse)(nil),      // 3: auth.v1.VerifyOTPResponse
	(*RestoreAccountRequest)(nil),  // 4: auth.v1.RestoreAccountRequest
	(*RestoreAccountResponse)(nil), // 5: auth.v1.RestoreAccountResponse
	(*DeleteAccountRequest)(nil),   // 6: auth.v1.DeleteAccountRequest
	(*DeleteAccountResponse)(nil),  // 7: auth.v1.DeleteAccountResponse
	(*RefreshTokenRequest)(nil),    // 8: auth.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),   // 9: auth.v1.RefreshTokenResponse
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	0, // 0: auth.v1.AuthService.Login:input_type -> auth.v1.LoginRequest
	2, // 1: auth.v1.AuthService.VerifyOTP:input_type -> auth.v1.VerifyOTPRequest
	4, // 2: auth.v1.AuthService.RestoreAccount:input_type -> auth.v1.RestoreAccountRequest
	6, // 3: auth.v1.AuthService.DeleteAccount:input_type -> auth.v1.DeleteAccountRequest
	8, // 4: auth.v1.AuthService.RefreshToken:input_type -> auth.v1.RefreshTokenRequest
	1, // 5: auth.v1.AuthService.Login:output_type -> auth.v1.LoginResponse
	3, // 6: auth.v1.AuthService.VerifyOTP:output_type -> auth.v1.VerifyOTPResponse
	5, // 7: auth.v1.AuthService.RestoreAccount:output_type -> auth.v1.RestoreAccountResponse
	7, // 8: auth.v1.AuthService.DeleteAccount:output_type -> auth.v1.DeleteAccountResponse
	9, // 9: auth.v1.AuthService.RefreshToken:output_type -> auth.v1.RefreshTokenResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	file_auth_v1_auth_proto_msgTypes[0].OneofWrappers = []any{
		(*LoginRequest_Phone)(nil),
		(*LoginRequest_Email)(nil),
	}
	file_auth_v1_auth_proto_msgTypes[2].OneofWrappers = []any{
		(*VerifyOTPRequest_Phone)(nil),
		(*VerifyOTPRequest_Email)(nil),
	}
	file_auth_v1_auth_proto_msgTypes[4].OneofWrappers = []any{
		(*RestoreAccountRequest_Phone)(nil),
		(*RestoreAccountRequest_Email)(nil),
	}
	file_auth_v1_auth_proto_msgTypes[6].OneofWrappers = []any{
		(*DeleteAccountRequest_Phone)(nil),
		(*DeleteAccountRequest_Email)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
