// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: events/users/v1/users.proto

package users_events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRegistered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegistered) Reset() {
	*x = UserRegistered{}
	mi := &file_events_users_v1_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegistered) ProtoMessage() {}

func (x *UserRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_events_users_v1_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegistered.ProtoReflect.Descriptor instead.
func (*UserRegistered) Descriptor() ([]byte, []int) {
	return file_events_users_v1_users_proto_rawDescGZIP(), []int{0}
}

func (x *UserRegistered) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ContactRegistered struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Types that are valid to be assigned to Contact:
	//
	//	*ContactRegistered_Phone
	//	*ContactRegistered_Email
	Contact       isContactRegistered_Contact `protobuf_oneof:"contact"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactRegistered) Reset() {
	*x = ContactRegistered{}
	mi := &file_events_users_v1_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactRegistered) ProtoMessage() {}

func (x *ContactRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_events_users_v1_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactRegistered.ProtoReflect.Descriptor instead.
func (*ContactRegistered) Descriptor() ([]byte, []int) {
	return file_events_users_v1_users_proto_rawDescGZIP(), []int{1}
}

func (x *ContactRegistered) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ContactRegistered) GetContact() isContactRegistered_Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *ContactRegistered) GetPhone() string {
	if x != nil {
		if x, ok := x.Contact.(*ContactRegistered_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

func (x *ContactRegistered) GetEmail() string {
	if x != nil {
		if x, ok := x.Contact.(*ContactRegistered_Email); ok {
			return x.Email
		}
	}
	return ""
}

type isContactRegistered_Contact interface {
	isContactRegistered_Contact()
}

type ContactRegistered_Phone struct {
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3,oneof"`
}

type ContactRegistered_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

func (*ContactRegistered_Phone) isContactRegistered_Contact() {}

func (*ContactRegistered_Email) isContactRegistered_Contact() {}

type UserUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdated) Reset() {
	*x = UserUpdated{}
	mi := &file_events_users_v1_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdated) ProtoMessage() {}

func (x *UserUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_events_users_v1_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdated.ProtoReflect.Descriptor instead.
func (*UserUpdated) Descriptor() ([]byte, []int) {
	return file_events_users_v1_users_proto_rawDescGZIP(), []int{2}
}

func (x *UserUpdated) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserUpdated) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *UserUpdated) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UserDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleted) Reset() {
	*x = UserDeleted{}
	mi := &file_events_users_v1_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleted) ProtoMessage() {}

func (x *UserDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_events_users_v1_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleted.ProtoReflect.Descriptor instead.
func (*UserDeleted) Descriptor() ([]byte, []int) {
	return file_events_users_v1_users_proto_rawDescGZIP(), []int{3}
}

type UserRestored struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRestored) Reset() {
	*x = UserRestored{}
	mi := &file_events_users_v1_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRestored) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRestored) ProtoMessage() {}

func (x *UserRestored) ProtoReflect() protoreflect.Message {
	mi := &file_events_users_v1_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRestored.ProtoReflect.Descriptor instead.
func (*UserRestored) Descriptor() ([]byte, []int) {
	return file_events_users_v1_users_proto_rawDescGZIP(), []int{4}
}

var File_events_users_v1_users_proto protoreflect.FileDescriptor

const file_events_users_v1_users_proto_rawDesc = "" +
	"\n" +
	"\x1bevents/users/v1/users.proto\x12\x0fevents.users.v1\" \n" +
	"\x0eUserRegistered\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"g\n" +
	"\x11ContactRegistered\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x05phone\x18\x02 \x01(\tH\x00R\x05phone\x12\x16\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05emailB\t\n" +
	"\acontact\"R\n" +
	"\vUserUpdated\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\r\n" +
	"\vUserDeleted\"\x0e\n" +
	"\fUserRestoredB\"Z shared/events/users;users_eventsb\x06proto3"

var (
	file_events_users_v1_users_proto_rawDescOnce sync.Once
	file_events_users_v1_users_proto_rawDescData []byte
)

func file_events_users_v1_users_proto_rawDescGZIP() []byte {
	file_events_users_v1_users_proto_rawDescOnce.Do(func() {
		file_events_users_v1_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_users_v1_users_proto_rawDesc), len(file_events_users_v1_users_proto_rawDesc)))
	})
	return file_events_users_v1_users_proto_rawDescData
}

var file_events_users_v1_users_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_events_users_v1_users_proto_goTypes = []any{
	(*UserRegistered)(nil),    // 0: events.users.v1.UserRegistered
	(*ContactRegistered)(nil), // 1: events.users.v1.ContactRegistered
	(*UserUpdated)(nil),       // 2: events.users.v1.UserUpdated
	(*UserDeleted)(nil),       // 3: events.users.v1.UserDeleted
	(*UserRestored)(nil),      // 4: events.users.v1.UserRestored
}
var file_events_users_v1_users_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_users_v1_users_proto_init() }
func file_events_users_v1_users_proto_init() {
	if File_events_users_v1_users_proto != nil {
		return
	}
	file_events_users_v1_users_proto_msgTypes[1].OneofWrappers = []any{
		(*ContactRegistered_Phone)(nil),
		(*ContactRegistered_Email)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_users_v1_users_proto_rawDesc), len(file_events_users_v1_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_users_v1_users_proto_goTypes,
		DependencyIndexes: file_events_users_v1_users_proto_depIdxs,
		MessageInfos:      file_events_users_v1_users_proto_msgTypes,
	}.Build()
	File_events_users_v1_users_proto = out.File
	file_events_users_v1_users_proto_goTypes = nil
	file_events_users_v1_users_proto_depIdxs = nil
}
