apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_DB: auth_db
  POSTGRES_USER: auth_admin
  POSTGRES_PASSWORD: secret_password
