// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: user/users.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Visibility int32

const (
	Visibility_EVERYONE Visibility = 0
	Visibility_FRIENDS  Visibility = 1
	Visibility_CONTACTS Visibility = 2
	Visibility_NOBODY   Visibility = 3
)

// Enum value maps for Visibility.
var (
	Visibility_name = map[int32]string{
		0: "EVERYONE",
		1: "FRIENDS",
		2: "CONTACTS",
		3: "NOBODY",
	}
	Visibility_value = map[string]int32{
		"EVERYONE": 0,
		"FRIENDS":  1,
		"CONTACTS": 2,
		"NOBODY":   3,
	}
)

func (x Visibility) Enum() *Visibility {
	p := new(Visibility)
	*p = x
	return p
}

func (x Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_user_users_proto_enumTypes[0].Descriptor()
}

func (Visibility) Type() protoreflect.EnumType {
	return &file_user_users_proto_enumTypes[0]
}

func (x Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Visibility.Descriptor instead.
func (Visibility) EnumDescriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{0}
}

type AccountBadge int32

const (
	AccountBadge_UNVERIFIED   AccountBadge = 0
	AccountBadge_BLUE_BADGE   AccountBadge = 1
	AccountBadge_GOLD_BADGE   AccountBadge = 2
	AccountBadge_SILVER_BADGE AccountBadge = 3
)

// Enum value maps for AccountBadge.
var (
	AccountBadge_name = map[int32]string{
		0: "UNVERIFIED",
		1: "BLUE_BADGE",
		2: "GOLD_BADGE",
		3: "SILVER_BADGE",
	}
	AccountBadge_value = map[string]int32{
		"UNVERIFIED":   0,
		"BLUE_BADGE":   1,
		"GOLD_BADGE":   2,
		"SILVER_BADGE": 3,
	}
)

func (x AccountBadge) Enum() *AccountBadge {
	p := new(AccountBadge)
	*p = x
	return p
}

func (x AccountBadge) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountBadge) Descriptor() protoreflect.EnumDescriptor {
	return file_user_users_proto_enumTypes[1].Descriptor()
}

func (AccountBadge) Type() protoreflect.EnumType {
	return &file_user_users_proto_enumTypes[1]
}

func (x AccountBadge) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountBadge.Descriptor instead.
func (AccountBadge) EnumDescriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{1}
}

type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username        string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName     string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email           string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone           string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	ProfileImageUrl string                 `protobuf:"bytes,6,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	Bio             string                 `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	BioStatus       string                 `protobuf:"bytes,8,opt,name=bio_status,json=bioStatus,proto3" json:"bio_status,omitempty"`
	EmailVerified   bool                   `protobuf:"varint,9,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	PhoneVerified   bool                   `protobuf:"varint,10,opt,name=phone_verified,json=phoneVerified,proto3" json:"phone_verified,omitempty"`
	AccountBadge    AccountBadge           `protobuf:"varint,11,opt,name=account_badge,json=accountBadge,proto3,enum=users.AccountBadge" json:"account_badge,omitempty"`
	BirthDate       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetProfileImageUrl() string {
	if x != nil {
		return x.ProfileImageUrl
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetBioStatus() string {
	if x != nil {
		return x.BioStatus
	}
	return ""
}

func (x *User) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *User) GetPhoneVerified() bool {
	if x != nil {
		return x.PhoneVerified
	}
	return false
}

func (x *User) GetAccountBadge() AccountBadge {
	if x != nil {
		return x.AccountBadge
	}
	return AccountBadge_UNVERIFIED
}

func (x *User) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UserSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username        string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName     string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ProfileImageUrl string                 `protobuf:"bytes,4,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	AccountBadge    AccountBadge           `protobuf:"varint,5,opt,name=account_badge,json=accountBadge,proto3,enum=users.AccountBadge" json:"account_badge,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserSummary) Reset() {
	*x = UserSummary{}
	mi := &file_user_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummary) ProtoMessage() {}

func (x *UserSummary) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummary.ProtoReflect.Descriptor instead.
func (*UserSummary) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{1}
}

func (x *UserSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserSummary) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserSummary) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserSummary) GetProfileImageUrl() string {
	if x != nil {
		return x.ProfileImageUrl
	}
	return ""
}

func (x *UserSummary) GetAccountBadge() AccountBadge {
	if x != nil {
		return x.AccountBadge
	}
	return AccountBadge_UNVERIFIED
}

type PrivacySettings struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AvatarVisibility    Visibility             `protobuf:"varint,1,opt,name=avatar_visibility,json=avatarVisibility,proto3,enum=users.Visibility" json:"avatar_visibility,omitempty"`
	PhoneVisibility     Visibility             `protobuf:"varint,2,opt,name=phone_visibility,json=phoneVisibility,proto3,enum=users.Visibility" json:"phone_visibility,omitempty"`
	EmailVisibility     Visibility             `protobuf:"varint,3,opt,name=email_visibility,json=emailVisibility,proto3,enum=users.Visibility" json:"email_visibility,omitempty"`
	LastSeenVisibility  Visibility             `protobuf:"varint,4,opt,name=last_seen_visibility,json=lastSeenVisibility,proto3,enum=users.Visibility" json:"last_seen_visibility,omitempty"`
	ReadReceiptsEnabled bool                   `protobuf:"varint,5,opt,name=read_receipts_enabled,json=readReceiptsEnabled,proto3" json:"read_receipts_enabled,omitempty"`
	FindByUsername      bool                   `protobuf:"varint,6,opt,name=find_by_username,json=findByUsername,proto3" json:"find_by_username,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PrivacySettings) Reset() {
	*x = PrivacySettings{}
	mi := &file_user_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivacySettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivacySettings) ProtoMessage() {}

func (x *PrivacySettings) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivacySettings.ProtoReflect.Descriptor instead.
func (*PrivacySettings) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{2}
}

func (x *PrivacySettings) GetAvatarVisibility() Visibility {
	if x != nil {
		return x.AvatarVisibility
	}
	return Visibility_EVERYONE
}

func (x *PrivacySettings) GetPhoneVisibility() Visibility {
	if x != nil {
		return x.PhoneVisibility
	}
	return Visibility_EVERYONE
}

func (x *PrivacySettings) GetEmailVisibility() Visibility {
	if x != nil {
		return x.EmailVisibility
	}
	return Visibility_EVERYONE
}

func (x *PrivacySettings) GetLastSeenVisibility() Visibility {
	if x != nil {
		return x.LastSeenVisibility
	}
	return Visibility_EVERYONE
}

func (x *PrivacySettings) GetReadReceiptsEnabled() bool {
	if x != nil {
		return x.ReadReceiptsEnabled
	}
	return false
}

func (x *PrivacySettings) GetFindByUsername() bool {
	if x != nil {
		return x.FindByUsername
	}
	return false
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	DisplayName   string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateUserRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_user_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Id              string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username        *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName     *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email           *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone           *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	ProfileImageUrl *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	Bio             *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	BioStatus       *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=bio_status,json=bioStatus,proto3" json:"bio_status,omitempty"`
	BirthDate       *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetUsername() *wrapperspb.StringValue {
	if x != nil {
		return x.Username
	}
	return nil
}

func (x *UpdateUserRequest) GetDisplayName() *wrapperspb.StringValue {
	if x != nil {
		return x.DisplayName
	}
	return nil
}

func (x *UpdateUserRequest) GetEmail() *wrapperspb.StringValue {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *UpdateUserRequest) GetPhone() *wrapperspb.StringValue {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *UpdateUserRequest) GetProfileImageUrl() *wrapperspb.StringValue {
	if x != nil {
		return x.ProfileImageUrl
	}
	return nil
}

func (x *UpdateUserRequest) GetBio() *wrapperspb.StringValue {
	if x != nil {
		return x.Bio
	}
	return nil
}

func (x *UpdateUserRequest) GetBioStatus() *wrapperspb.StringValue {
	if x != nil {
		return x.BioStatus
	}
	return nil
}

func (x *UpdateUserRequest) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_user_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_user_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_user_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{8}
}

type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Lookup:
	//
	//	*GetUserRequest_Id
	//	*GetUserRequest_Username
	//	*GetUserRequest_Email
	//	*GetUserRequest_Phone
	Lookup        isGetUserRequest_Lookup `protobuf_oneof:"lookup"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserRequest) GetLookup() isGetUserRequest_Lookup {
	if x != nil {
		return x.Lookup
	}
	return nil
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		if x, ok := x.Lookup.(*GetUserRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *GetUserRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.Lookup.(*GetUserRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *GetUserRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Lookup.(*GetUserRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *GetUserRequest) GetPhone() string {
	if x != nil {
		if x, ok := x.Lookup.(*GetUserRequest_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

type isGetUserRequest_Lookup interface {
	isGetUserRequest_Lookup()
}

type GetUserRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetUserRequest_Username struct {
	Username string `protobuf:"bytes,2,opt,name=username,proto3,oneof"`
}

type GetUserRequest_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

type GetUserRequest_Phone struct {
	Phone string `protobuf:"bytes,4,opt,name=phone,proto3,oneof"`
}

func (*GetUserRequest_Id) isGetUserRequest_Lookup() {}

func (*GetUserRequest_Username) isGetUserRequest_Lookup() {}

func (*GetUserRequest_Email) isGetUserRequest_Lookup() {}

func (*GetUserRequest_Phone) isGetUserRequest_Lookup() {}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_user_users_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_user_users_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{11}
}

func (x *GetUsersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_user_users_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{12}
}

func (x *GetUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetUserSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSummaryRequest) Reset() {
	*x = GetUserSummaryRequest{}
	mi := &file_user_users_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSummaryRequest) ProtoMessage() {}

func (x *GetUserSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetUserSummaryRequest) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserSummaryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserSummary           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSummaryResponse) Reset() {
	*x = GetUserSummaryResponse{}
	mi := &file_user_users_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSummaryResponse) ProtoMessage() {}

func (x *GetUserSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetUserSummaryResponse) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserSummaryResponse) GetUser() *UserSummary {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUsersSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersSummaryRequest) Reset() {
	*x = GetUsersSummaryRequest{}
	mi := &file_user_users_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersSummaryRequest) ProtoMessage() {}

func (x *GetUsersSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetUsersSummaryRequest) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{15}
}

func (x *GetUsersSummaryRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetUsersSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserSummary         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersSummaryResponse) Reset() {
	*x = GetUsersSummaryResponse{}
	mi := &file_user_users_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersSummaryResponse) ProtoMessage() {}

func (x *GetUsersSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetUsersSummaryResponse) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{16}
}

func (x *GetUsersSummaryResponse) GetUsers() []*UserSummary {
	if x != nil {
		return x.Users
	}
	return nil
}

type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_user_users_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{17}
}

func (x *SearchUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsersRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchUsersRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserSummary         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalResults  uint32                 `protobuf:"varint,2,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResponse) Reset() {
	*x = SearchUsersResponse{}
	mi := &file_user_users_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResponse) ProtoMessage() {}

func (x *SearchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{18}
}

func (x *SearchUsersResponse) GetUsers() []*UserSummary {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SearchUsersResponse) GetTotalResults() uint32 {
	if x != nil {
		return x.TotalResults
	}
	return 0
}

func (x *SearchUsersResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type UserExistsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Lookup:
	//
	//	*UserExistsRequest_Id
	//	*UserExistsRequest_Username
	//	*UserExistsRequest_Email
	//	*UserExistsRequest_Phone
	Lookup        isUserExistsRequest_Lookup `protobuf_oneof:"lookup"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserExistsRequest) Reset() {
	*x = UserExistsRequest{}
	mi := &file_user_users_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExistsRequest) ProtoMessage() {}

func (x *UserExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExistsRequest.ProtoReflect.Descriptor instead.
func (*UserExistsRequest) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{19}
}

func (x *UserExistsRequest) GetLookup() isUserExistsRequest_Lookup {
	if x != nil {
		return x.Lookup
	}
	return nil
}

func (x *UserExistsRequest) GetId() string {
	if x != nil {
		if x, ok := x.Lookup.(*UserExistsRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *UserExistsRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.Lookup.(*UserExistsRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *UserExistsRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Lookup.(*UserExistsRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *UserExistsRequest) GetPhone() string {
	if x != nil {
		if x, ok := x.Lookup.(*UserExistsRequest_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

type isUserExistsRequest_Lookup interface {
	isUserExistsRequest_Lookup()
}

type UserExistsRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type UserExistsRequest_Username struct {
	Username string `protobuf:"bytes,2,opt,name=username,proto3,oneof"`
}

type UserExistsRequest_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

type UserExistsRequest_Phone struct {
	Phone string `protobuf:"bytes,4,opt,name=phone,proto3,oneof"`
}

func (*UserExistsRequest_Id) isUserExistsRequest_Lookup() {}

func (*UserExistsRequest_Username) isUserExistsRequest_Lookup() {}

func (*UserExistsRequest_Email) isUserExistsRequest_Lookup() {}

func (*UserExistsRequest_Phone) isUserExistsRequest_Lookup() {}

type UserExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserExistsResponse) Reset() {
	*x = UserExistsResponse{}
	mi := &file_user_users_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExistsResponse) ProtoMessage() {}

func (x *UserExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExistsResponse.ProtoReflect.Descriptor instead.
func (*UserExistsResponse) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{20}
}

func (x *UserExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type UsersExistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersExistRequest) Reset() {
	*x = UsersExistRequest{}
	mi := &file_user_users_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersExistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersExistRequest) ProtoMessage() {}

func (x *UsersExistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersExistRequest.ProtoReflect.Descriptor instead.
func (*UsersExistRequest) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{21}
}

func (x *UsersExistRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type UserExistence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserExistence) Reset() {
	*x = UserExistence{}
	mi := &file_user_users_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserExistence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExistence) ProtoMessage() {}

func (x *UserExistence) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExistence.ProtoReflect.Descriptor instead.
func (*UserExistence) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{22}
}

func (x *UserExistence) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserExistence) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type UsersExistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserExistence       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersExistResponse) Reset() {
	*x = UsersExistResponse{}
	mi := &file_user_users_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersExistResponse) ProtoMessage() {}

func (x *UsersExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersExistResponse.ProtoReflect.Descriptor instead.
func (*UsersExistResponse) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{23}
}

func (x *UsersExistResponse) GetUsers() []*UserExistence {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetPrivacySettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivacySettingsRequest) Reset() {
	*x = GetPrivacySettingsRequest{}
	mi := &file_user_users_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivacySettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivacySettingsRequest) ProtoMessage() {}

func (x *GetPrivacySettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivacySettingsRequest.ProtoReflect.Descriptor instead.
func (*GetPrivacySettingsRequest) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{24}
}

func (x *GetPrivacySettingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPrivacySettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *PrivacySettings       `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivacySettingsResponse) Reset() {
	*x = GetPrivacySettingsResponse{}
	mi := &file_user_users_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivacySettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivacySettingsResponse) ProtoMessage() {}

func (x *GetPrivacySettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivacySettingsResponse.ProtoReflect.Descriptor instead.
func (*GetPrivacySettingsResponse) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{25}
}

func (x *GetPrivacySettingsResponse) GetSettings() *PrivacySettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdatePrivacySettingsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AvatarVisibility    *wrapperspb.Int32Value `protobuf:"bytes,2,opt,name=avatar_visibility,json=avatarVisibility,proto3" json:"avatar_visibility,omitempty"`
	PhoneVisibility     *wrapperspb.Int32Value `protobuf:"bytes,3,opt,name=phone_visibility,json=phoneVisibility,proto3" json:"phone_visibility,omitempty"`
	EmailVisibility     *wrapperspb.Int32Value `protobuf:"bytes,4,opt,name=email_visibility,json=emailVisibility,proto3" json:"email_visibility,omitempty"`
	LastSeenVisibility  *wrapperspb.Int32Value `protobuf:"bytes,5,opt,name=last_seen_visibility,json=lastSeenVisibility,proto3" json:"last_seen_visibility,omitempty"`
	ReadReceiptsEnabled bool                   `protobuf:"varint,6,opt,name=read_receipts_enabled,json=readReceiptsEnabled,proto3" json:"read_receipts_enabled,omitempty"`
	FindByUsername      bool                   `protobuf:"varint,7,opt,name=find_by_username,json=findByUsername,proto3" json:"find_by_username,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdatePrivacySettingsRequest) Reset() {
	*x = UpdatePrivacySettingsRequest{}
	mi := &file_user_users_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePrivacySettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePrivacySettingsRequest) ProtoMessage() {}

func (x *UpdatePrivacySettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePrivacySettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdatePrivacySettingsRequest) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{26}
}

func (x *UpdatePrivacySettingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePrivacySettingsRequest) GetAvatarVisibility() *wrapperspb.Int32Value {
	if x != nil {
		return x.AvatarVisibility
	}
	return nil
}

func (x *UpdatePrivacySettingsRequest) GetPhoneVisibility() *wrapperspb.Int32Value {
	if x != nil {
		return x.PhoneVisibility
	}
	return nil
}

func (x *UpdatePrivacySettingsRequest) GetEmailVisibility() *wrapperspb.Int32Value {
	if x != nil {
		return x.EmailVisibility
	}
	return nil
}

func (x *UpdatePrivacySettingsRequest) GetLastSeenVisibility() *wrapperspb.Int32Value {
	if x != nil {
		return x.LastSeenVisibility
	}
	return nil
}

func (x *UpdatePrivacySettingsRequest) GetReadReceiptsEnabled() bool {
	if x != nil {
		return x.ReadReceiptsEnabled
	}
	return false
}

func (x *UpdatePrivacySettingsRequest) GetFindByUsername() bool {
	if x != nil {
		return x.FindByUsername
	}
	return false
}

type UpdatePrivacySettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *PrivacySettings       `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePrivacySettingsResponse) Reset() {
	*x = UpdatePrivacySettingsResponse{}
	mi := &file_user_users_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePrivacySettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePrivacySettingsResponse) ProtoMessage() {}

func (x *UpdatePrivacySettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePrivacySettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdatePrivacySettingsResponse) Descriptor() ([]byte, []int) {
	return file_user_users_proto_rawDescGZIP(), []int{27}
}

func (x *UpdatePrivacySettingsResponse) GetSettings() *PrivacySettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

var File_user_users_proto protoreflect.FileDescriptor

const file_user_users_proto_rawDesc = "" +
	"\n" +
	"\x10user/users.proto\x12\x05users\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x97\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12*\n" +
	"\x11profile_image_url\x18\x06 \x01(\tR\x0fprofileImageUrl\x12\x10\n" +
	"\x03bio\x18\a \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"bio_status\x18\b \x01(\tR\tbioStatus\x12%\n" +
	"\x0eemail_verified\x18\t \x01(\bR\remailVerified\x12%\n" +
	"\x0ephone_verified\x18\n" +
	" \x01(\bR\rphoneVerified\x128\n" +
	"\raccount_badge\x18\v \x01(\x0e2\x13.users.AccountBadgeR\faccountBadge\x129\n" +
	"\n" +
	"birth_date\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tbirthDate\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc2\x01\n" +
	"\vUserSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12*\n" +
	"\x11profile_image_url\x18\x04 \x01(\tR\x0fprofileImageUrl\x128\n" +
	"\raccount_badge\x18\x05 \x01(\x0e2\x13.users.AccountBadgeR\faccountBadge\"\xf0\x02\n" +
	"\x0fPrivacySettings\x12>\n" +
	"\x11avatar_visibility\x18\x01 \x01(\x0e2\x11.users.VisibilityR\x10avatarVisibility\x12<\n" +
	"\x10phone_visibility\x18\x02 \x01(\x0e2\x11.users.VisibilityR\x0fphoneVisibility\x12<\n" +
	"\x10email_visibility\x18\x03 \x01(\x0e2\x11.users.VisibilityR\x0femailVisibility\x12C\n" +
	"\x14last_seen_visibility\x18\x04 \x01(\x0e2\x11.users.VisibilityR\x12lastSeenVisibility\x122\n" +
	"\x15read_receipts_enabled\x18\x05 \x01(\bR\x13readReceiptsEnabled\x12(\n" +
	"\x10find_by_username\x18\x06 \x01(\bR\x0efindByUsername\"\x8e\x01\n" +
	"\x11CreateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\"5\n" +
	"\x12CreateUserResponse\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.users.UserR\x04user\"\xf8\x03\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\busername\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\busername\x12?\n" +
	"\fdisplay_name\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\vdisplayName\x122\n" +
	"\x05email\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x05email\x122\n" +
	"\x05phone\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x05phone\x12H\n" +
	"\x11profile_image_url\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x0fprofileImageUrl\x12.\n" +
	"\x03bio\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\x03bio\x12;\n" +
	"\n" +
	"bio_status\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\tbioStatus\x129\n" +
	"\n" +
	"birth_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tbirthDate\"5\n" +
	"\x12UpdateUserResponse\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.users.UserR\x04user\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteUserResponse\"z\n" +
	"\x0eGetUserRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x1c\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x12\x16\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05email\x12\x16\n" +
	"\x05phone\x18\x04 \x01(\tH\x00R\x05phoneB\b\n" +
	"\x06lookup\"2\n" +
	"\x0fGetUserResponse\x12\x1f\n" +
	"\x04user\x18\x01 \x01(\v2\v.users.UserR\x04user\",\n" +
	"\x0fGetUsersRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"5\n" +
	"\x10GetUsersResponse\x12!\n" +
	"\x05users\x18\x01 \x03(\v2\v.users.UserR\x05users\"'\n" +
	"\x15GetUserSummaryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x16GetUserSummaryResponse\x12&\n" +
	"\x04user\x18\x01 \x01(\v2\x12.users.UserSummaryR\x04user\"3\n" +
	"\x16GetUsersSummaryRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"C\n" +
	"\x17GetUsersSummaryResponse\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.users.UserSummaryR\x05users\"[\n" +
	"\x12SearchUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\"\x7f\n" +
	"\x13SearchUsersResponse\x12(\n" +
	"\x05users\x18\x01 \x03(\v2\x12.users.UserSummaryR\x05users\x12#\n" +
	"\rtotal_results\x18\x02 \x01(\rR\ftotalResults\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"}\n" +
	"\x11UserExistsRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x1c\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x12\x16\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05email\x12\x16\n" +
	"\x05phone\x18\x04 \x01(\tH\x00R\x05phoneB\b\n" +
	"\x06lookup\",\n" +
	"\x12UserExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\".\n" +
	"\x11UsersExistRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"@\n" +
	"\rUserExistence\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"@\n" +
	"\x12UsersExistResponse\x12*\n" +
	"\x05users\x18\x01 \x03(\v2\x14.users.UserExistenceR\x05users\"4\n" +
	"\x19GetPrivacySettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"P\n" +
	"\x1aGetPrivacySettingsResponse\x122\n" +
	"\bsettings\x18\x01 \x01(\v2\x16.users.PrivacySettingsR\bsettings\"\xbe\x03\n" +
	"\x1cUpdatePrivacySettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12H\n" +
	"\x11avatar_visibility\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\x10avatarVisibility\x12F\n" +
	"\x10phone_visibility\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\x0fphoneVisibility\x12F\n" +
	"\x10email_visibility\x18\x04 \x01(\v2\x1b.google.protobuf.Int32ValueR\x0femailVisibility\x12M\n" +
	"\x14last_seen_visibility\x18\x05 \x01(\v2\x1b.google.protobuf.Int32ValueR\x12lastSeenVisibility\x122\n" +
	"\x15read_receipts_enabled\x18\x06 \x01(\bR\x13readReceiptsEnabled\x12(\n" +
	"\x10find_by_username\x18\a \x01(\bR\x0efindByUsername\"S\n" +
	"\x1dUpdatePrivacySettingsResponse\x122\n" +
	"\bsettings\x18\x01 \x01(\v2\x16.users.PrivacySettingsR\bsettings*A\n" +
	"\n" +
	"Visibility\x12\f\n" +
	"\bEVERYONE\x10\x00\x12\v\n" +
	"\aFRIENDS\x10\x01\x12\f\n" +
	"\bCONTACTS\x10\x02\x12\n" +
	"\n" +
	"\x06NOBODY\x10\x03*P\n" +
	"\fAccountBadge\x12\x0e\n" +
	"\n" +
	"UNVERIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"BLUE_BADGE\x10\x01\x12\x0e\n" +
	"\n" +
	"GOLD_BADGE\x10\x02\x12\x10\n" +
	"\fSILVER_BADGE\x10\x032\xfa\x06\n" +
	"\fUsersService\x12A\n" +
	"\n" +
	"CreateUser\x12\x18.users.CreateUserRequest\x1a\x19.users.CreateUserResponse\x12A\n" +
	"\n" +
	"UpdateUser\x12\x18.users.UpdateUserRequest\x1a\x19.users.UpdateUserResponse\x12A\n" +
	"\n" +
	"DeleteUser\x12\x18.users.DeleteUserRequest\x1a\x19.users.DeleteUserResponse\x128\n" +
	"\aGetUser\x12\x15.users.GetUserRequest\x1a\x16.users.GetUserResponse\x12;\n" +
	"\bGetUsers\x12\x16.users.GetUsersRequest\x1a\x17.users.GetUsersResponse\x12M\n" +
	"\x0eGetUserSummary\x12\x1c.users.GetUserSummaryRequest\x1a\x1d.users.GetUserSummaryResponse\x12P\n" +
	"\x0fGetUsersSummary\x12\x1d.users.GetUsersSummaryRequest\x1a\x1e.users.GetUsersSummaryResponse\x12D\n" +
	"\vSearchUsers\x12\x19.users.SearchUsersRequest\x1a\x1a.users.SearchUsersResponse\x12A\n" +
	"\n" +
	"UserExists\x12\x18.users.UserExistsRequest\x1a\x19.users.UserExistsResponse\x12A\n" +
	"\n" +
	"UsersExist\x12\x18.users.UsersExistRequest\x1a\x19.users.UsersExistResponse\x12Y\n" +
	"\x12GetPrivacySettings\x12 .users.GetPrivacySettingsRequest\x1a!.users.GetPrivacySettingsResponse\x12b\n" +
	"\x15UpdatePrivacySettings\x12#.users.UpdatePrivacySettingsRequest\x1a$.users.UpdatePrivacySettingsResponseB\x1aZ\x18shared/proto/users;usersb\x06proto3"

var (
	file_user_users_proto_rawDescOnce sync.Once
	file_user_users_proto_rawDescData []byte
)

func file_user_users_proto_rawDescGZIP() []byte {
	file_user_users_proto_rawDescOnce.Do(func() {
		file_user_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_users_proto_rawDesc), len(file_user_users_proto_rawDesc)))
	})
	return file_user_users_proto_rawDescData
}

var file_user_users_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_user_users_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_user_users_proto_goTypes = []any{
	(Visibility)(0),                       // 0: users.Visibility
	(AccountBadge)(0),                     // 1: users.AccountBadge
	(*User)(nil),                          // 2: users.User
	(*UserSummary)(nil),                   // 3: users.UserSummary
	(*PrivacySettings)(nil),               // 4: users.PrivacySettings
	(*CreateUserRequest)(nil),             // 5: users.CreateUserRequest
	(*CreateUserResponse)(nil),            // 6: users.CreateUserResponse
	(*UpdateUserRequest)(nil),             // 7: users.UpdateUserRequest
	(*UpdateUserResponse)(nil),            // 8: users.UpdateUserResponse
	(*DeleteUserRequest)(nil),             // 9: users.DeleteUserRequest
	(*DeleteUserResponse)(nil),            // 10: users.DeleteUserResponse
	(*GetUserRequest)(nil),                // 11: users.GetUserRequest
	(*GetUserResponse)(nil),               // 12: users.GetUserResponse
	(*GetUsersRequest)(nil),               // 13: users.GetUsersRequest
	(*GetUsersResponse)(nil),              // 14: users.GetUsersResponse
	(*GetUserSummaryRequest)(nil),         // 15: users.GetUserSummaryRequest
	(*GetUserSummaryResponse)(nil),        // 16: users.GetUserSummaryResponse
	(*GetUsersSummaryRequest)(nil),        // 17: users.GetUsersSummaryRequest
	(*GetUsersSummaryResponse)(nil),       // 18: users.GetUsersSummaryResponse
	(*SearchUsersRequest)(nil),            // 19: users.SearchUsersRequest
	(*SearchUsersResponse)(nil),           // 20: users.SearchUsersResponse
	(*UserExistsRequest)(nil),             // 21: users.UserExistsRequest
	(*UserExistsResponse)(nil),            // 22: users.UserExistsResponse
	(*UsersExistRequest)(nil),             // 23: users.UsersExistRequest
	(*UserExistence)(nil),                 // 24: users.UserExistence
	(*UsersExistResponse)(nil),            // 25: users.UsersExistResponse
	(*GetPrivacySettingsRequest)(nil),     // 26: users.GetPrivacySettingsRequest
	(*GetPrivacySettingsResponse)(nil),    // 27: users.GetPrivacySettingsResponse
	(*UpdatePrivacySettingsRequest)(nil),  // 28: users.UpdatePrivacySettingsRequest
	(*UpdatePrivacySettingsResponse)(nil), // 29: users.UpdatePrivacySettingsResponse
	(*timestamppb.Timestamp)(nil),         // 30: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil),        // 31: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),         // 32: google.protobuf.Int32Value
}
var file_user_users_proto_depIdxs = []int32{
	1,  // 0: users.User.account_badge:type_name -> users.AccountBadge
	30, // 1: users.User.birth_date:type_name -> google.protobuf.Timestamp
	30, // 2: users.User.created_at:type_name -> google.protobuf.Timestamp
	30, // 3: users.User.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: users.UserSummary.account_badge:type_name -> users.AccountBadge
	0,  // 5: users.PrivacySettings.avatar_visibility:type_name -> users.Visibility
	0,  // 6: users.PrivacySettings.phone_visibility:type_name -> users.Visibility
	0,  // 7: users.PrivacySettings.email_visibility:type_name -> users.Visibility
	0,  // 8: users.PrivacySettings.last_seen_visibility:type_name -> users.Visibility
	2,  // 9: users.CreateUserResponse.user:type_name -> users.User
	31, // 10: users.UpdateUserRequest.username:type_name -> google.protobuf.StringValue
	31, // 11: users.UpdateUserRequest.display_name:type_name -> google.protobuf.StringValue
	31, // 12: users.UpdateUserRequest.email:type_name -> google.protobuf.StringValue
	31, // 13: users.UpdateUserRequest.phone:type_name -> google.protobuf.StringValue
	31, // 14: users.UpdateUserRequest.profile_image_url:type_name -> google.protobuf.StringValue
	31, // 15: users.UpdateUserRequest.bio:type_name -> google.protobuf.StringValue
	31, // 16: users.UpdateUserRequest.bio_status:type_name -> google.protobuf.StringValue
	30, // 17: users.UpdateUserRequest.birth_date:type_name -> google.protobuf.Timestamp
	2,  // 18: users.UpdateUserResponse.user:type_name -> users.User
	2,  // 19: users.GetUserResponse.user:type_name -> users.User
	2,  // 20: users.GetUsersResponse.users:type_name -> users.User
	3,  // 21: users.GetUserSummaryResponse.user:type_name -> users.UserSummary
	3,  // 22: users.GetUsersSummaryResponse.users:type_name -> users.UserSummary
	3,  // 23: users.SearchUsersResponse.users:type_name -> users.UserSummary
	24, // 24: users.UsersExistResponse.users:type_name -> users.UserExistence
	4,  // 25: users.GetPrivacySettingsResponse.settings:type_name -> users.PrivacySettings
	32, // 26: users.UpdatePrivacySettingsRequest.avatar_visibility:type_name -> google.protobuf.Int32Value
	32, // 27: users.UpdatePrivacySettingsRequest.phone_visibility:type_name -> google.protobuf.Int32Value
	32, // 28: users.UpdatePrivacySettingsRequest.email_visibility:type_name -> google.protobuf.Int32Value
	32, // 29: users.UpdatePrivacySettingsRequest.last_seen_visibility:type_name -> google.protobuf.Int32Value
	4,  // 30: users.UpdatePrivacySettingsResponse.settings:type_name -> users.PrivacySettings
	5,  // 31: users.UsersService.CreateUser:input_type -> users.CreateUserRequest
	7,  // 32: users.UsersService.UpdateUser:input_type -> users.UpdateUserRequest
	9,  // 33: users.UsersService.DeleteUser:input_type -> users.DeleteUserRequest
	11, // 34: users.UsersService.GetUser:input_type -> users.GetUserRequest
	13, // 35: users.UsersService.GetUsers:input_type -> users.GetUsersRequest
	15, // 36: users.UsersService.GetUserSummary:input_type -> users.GetUserSummaryRequest
	17, // 37: users.UsersService.GetUsersSummary:input_type -> users.GetUsersSummaryRequest
	19, // 38: users.UsersService.SearchUsers:input_type -> users.SearchUsersRequest
	21, // 39: users.UsersService.UserExists:input_type -> users.UserExistsRequest
	23, // 40: users.UsersService.UsersExist:input_type -> users.UsersExistRequest
	26, // 41: users.UsersService.GetPrivacySettings:input_type -> users.GetPrivacySettingsRequest
	28, // 42: users.UsersService.UpdatePrivacySettings:input_type -> users.UpdatePrivacySettingsRequest
	6,  // 43: users.UsersService.CreateUser:output_type -> users.CreateUserResponse
	8,  // 44: users.UsersService.UpdateUser:output_type -> users.UpdateUserResponse
	10, // 45: users.UsersService.DeleteUser:output_type -> users.DeleteUserResponse
	12, // 46: users.UsersService.GetUser:output_type -> users.GetUserResponse
	14, // 47: users.UsersService.GetUsers:output_type -> users.GetUsersResponse
	16, // 48: users.UsersService.GetUserSummary:output_type -> users.GetUserSummaryResponse
	18, // 49: users.UsersService.GetUsersSummary:output_type -> users.GetUsersSummaryResponse
	20, // 50: users.UsersService.SearchUsers:output_type -> users.SearchUsersResponse
	22, // 51: users.UsersService.UserExists:output_type -> users.UserExistsResponse
	25, // 52: users.UsersService.UsersExist:output_type -> users.UsersExistResponse
	27, // 53: users.UsersService.GetPrivacySettings:output_type -> users.GetPrivacySettingsResponse
	29, // 54: users.UsersService.UpdatePrivacySettings:output_type -> users.UpdatePrivacySettingsResponse
	43, // [43:55] is the sub-list for method output_type
	31, // [31:43] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_user_users_proto_init() }
func file_user_users_proto_init() {
	if File_user_users_proto != nil {
		return
	}
	file_user_users_proto_msgTypes[9].OneofWrappers = []any{
		(*GetUserRequest_Id)(nil),
		(*GetUserRequest_Username)(nil),
		(*GetUserRequest_Email)(nil),
		(*GetUserRequest_Phone)(nil),
	}
	file_user_users_proto_msgTypes[19].OneofWrappers = []any{
		(*UserExistsRequest_Id)(nil),
		(*UserExistsRequest_Username)(nil),
		(*UserExistsRequest_Email)(nil),
		(*UserExistsRequest_Phone)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_users_proto_rawDesc), len(file_user_users_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_users_proto_goTypes,
		DependencyIndexes: file_user_users_proto_depIdxs,
		EnumInfos:         file_user_users_proto_enumTypes,
		MessageInfos:      file_user_users_proto_msgTypes,
	}.Build()
	File_user_users_proto = out.File
	file_user_users_proto_goTypes = nil
	file_user_users_proto_depIdxs = nil
}
