// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: users/v1/users.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Visibility int32

const (
	Visibility_EVERYONE Visibility = 0
	Visibility_FRIENDS  Visibility = 1
	Visibility_CONTACTS Visibility = 2
	Visibility_NOBODY   Visibility = 3
)

// Enum value maps for Visibility.
var (
	Visibility_name = map[int32]string{
		0: "EVERYONE",
		1: "FRIENDS",
		2: "CONTACTS",
		3: "NOBODY",
	}
	Visibility_value = map[string]int32{
		"EVERYONE": 0,
		"FRIENDS":  1,
		"CONTACTS": 2,
		"NOBODY":   3,
	}
)

func (x Visibility) Enum() *Visibility {
	p := new(Visibility)
	*p = x
	return p
}

func (x Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_users_v1_users_proto_enumTypes[0].Descriptor()
}

func (Visibility) Type() protoreflect.EnumType {
	return &file_users_v1_users_proto_enumTypes[0]
}

func (x Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Visibility.Descriptor instead.
func (Visibility) EnumDescriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{0}
}

type AccountBadge int32

const (
	AccountBadge_UNVERIFIED   AccountBadge = 0
	AccountBadge_BLUE_BADGE   AccountBadge = 1
	AccountBadge_GOLD_BADGE   AccountBadge = 2
	AccountBadge_SILVER_BADGE AccountBadge = 3
)

// Enum value maps for AccountBadge.
var (
	AccountBadge_name = map[int32]string{
		0: "UNVERIFIED",
		1: "BLUE_BADGE",
		2: "GOLD_BADGE",
		3: "SILVER_BADGE",
	}
	AccountBadge_value = map[string]int32{
		"UNVERIFIED":   0,
		"BLUE_BADGE":   1,
		"GOLD_BADGE":   2,
		"SILVER_BADGE": 3,
	}
)

func (x AccountBadge) Enum() *AccountBadge {
	p := new(AccountBadge)
	*p = x
	return p
}

func (x AccountBadge) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountBadge) Descriptor() protoreflect.EnumDescriptor {
	return file_users_v1_users_proto_enumTypes[1].Descriptor()
}

func (AccountBadge) Type() protoreflect.EnumType {
	return &file_users_v1_users_proto_enumTypes[1]
}

func (x AccountBadge) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountBadge.Descriptor instead.
func (AccountBadge) EnumDescriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{1}
}

type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username        string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName     string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email           string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone           string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	ProfileImageUrl string                 `protobuf:"bytes,6,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	Bio             string                 `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`
	BioStatus       string                 `protobuf:"bytes,8,opt,name=bio_status,json=bioStatus,proto3" json:"bio_status,omitempty"`
	AccountBadge    AccountBadge           `protobuf:"varint,9,opt,name=account_badge,json=accountBadge,proto3,enum=users.v1.AccountBadge" json:"account_badge,omitempty"`
	FriendsCount    uint32                 `protobuf:"varint,10,opt,name=friends_count,json=friendsCount,proto3" json:"friends_count,omitempty"`
	FollowersCount  uint32                 `protobuf:"varint,11,opt,name=followers_count,json=followersCount,proto3" json:"followers_count,omitempty"`
	FollowingCount  uint32                 `protobuf:"varint,12,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	PostsCount      uint32                 `protobuf:"varint,13,opt,name=posts_count,json=postsCount,proto3" json:"posts_count,omitempty"`
	BirthDate       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_users_v1_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetProfileImageUrl() string {
	if x != nil {
		return x.ProfileImageUrl
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetBioStatus() string {
	if x != nil {
		return x.BioStatus
	}
	return ""
}

func (x *User) GetAccountBadge() AccountBadge {
	if x != nil {
		return x.AccountBadge
	}
	return AccountBadge_UNVERIFIED
}

func (x *User) GetFriendsCount() uint32 {
	if x != nil {
		return x.FriendsCount
	}
	return 0
}

func (x *User) GetFollowersCount() uint32 {
	if x != nil {
		return x.FollowersCount
	}
	return 0
}

func (x *User) GetFollowingCount() uint32 {
	if x != nil {
		return x.FollowingCount
	}
	return 0
}

func (x *User) GetPostsCount() uint32 {
	if x != nil {
		return x.PostsCount
	}
	return 0
}

func (x *User) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UserSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username        string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName     string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	PhoneNumber     string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	ProfileImageUrl string                 `protobuf:"bytes,5,opt,name=profile_image_url,json=profileImageUrl,proto3" json:"profile_image_url,omitempty"`
	AccountBadge    AccountBadge           `protobuf:"varint,6,opt,name=account_badge,json=accountBadge,proto3,enum=users.v1.AccountBadge" json:"account_badge,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserSummary) Reset() {
	*x = UserSummary{}
	mi := &file_users_v1_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummary) ProtoMessage() {}

func (x *UserSummary) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummary.ProtoReflect.Descriptor instead.
func (*UserSummary) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{1}
}

func (x *UserSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserSummary) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserSummary) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserSummary) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserSummary) GetProfileImageUrl() string {
	if x != nil {
		return x.ProfileImageUrl
	}
	return ""
}

func (x *UserSummary) GetAccountBadge() AccountBadge {
	if x != nil {
		return x.AccountBadge
	}
	return AccountBadge_UNVERIFIED
}

type PrivacySettings struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AvatarVisibility    Visibility             `protobuf:"varint,1,opt,name=avatar_visibility,json=avatarVisibility,proto3,enum=users.v1.Visibility" json:"avatar_visibility,omitempty"`
	PhoneVisibility     Visibility             `protobuf:"varint,2,opt,name=phone_visibility,json=phoneVisibility,proto3,enum=users.v1.Visibility" json:"phone_visibility,omitempty"`
	EmailVisibility     Visibility             `protobuf:"varint,3,opt,name=email_visibility,json=emailVisibility,proto3,enum=users.v1.Visibility" json:"email_visibility,omitempty"`
	LastSeenVisibility  Visibility             `protobuf:"varint,4,opt,name=last_seen_visibility,json=lastSeenVisibility,proto3,enum=users.v1.Visibility" json:"last_seen_visibility,omitempty"`
	ReadReceiptsEnabled bool                   `protobuf:"varint,5,opt,name=read_receipts_enabled,json=readReceiptsEnabled,proto3" json:"read_receipts_enabled,omitempty"`
	FindByUsername      bool                   `protobuf:"varint,6,opt,name=find_by_username,json=findByUsername,proto3" json:"find_by_username,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PrivacySettings) Reset() {
	*x = PrivacySettings{}
	mi := &file_users_v1_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivacySettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivacySettings) ProtoMessage() {}

func (x *PrivacySettings) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivacySettings.ProtoReflect.Descriptor instead.
func (*PrivacySettings) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{2}
}

func (x *PrivacySettings) GetAvatarVisibility() Visibility {
	if x != nil {
		return x.AvatarVisibility
	}
	return Visibility_EVERYONE
}

func (x *PrivacySettings) GetPhoneVisibility() Visibility {
	if x != nil {
		return x.PhoneVisibility
	}
	return Visibility_EVERYONE
}

func (x *PrivacySettings) GetEmailVisibility() Visibility {
	if x != nil {
		return x.EmailVisibility
	}
	return Visibility_EVERYONE
}

func (x *PrivacySettings) GetLastSeenVisibility() Visibility {
	if x != nil {
		return x.LastSeenVisibility
	}
	return Visibility_EVERYONE
}

func (x *PrivacySettings) GetReadReceiptsEnabled() bool {
	if x != nil {
		return x.ReadReceiptsEnabled
	}
	return false
}

func (x *PrivacySettings) GetFindByUsername() bool {
	if x != nil {
		return x.FindByUsername
	}
	return false
}

type CreateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Contact:
	//
	//	*CreateUserRequest_Email
	//	*CreateUserRequest_Phone
	Contact       isCreateUserRequest_Contact `protobuf_oneof:"contact"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_users_v1_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserRequest) GetContact() isCreateUserRequest_Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Contact.(*CreateUserRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *CreateUserRequest) GetPhone() string {
	if x != nil {
		if x, ok := x.Contact.(*CreateUserRequest_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

type isCreateUserRequest_Contact interface {
	isCreateUserRequest_Contact()
}

type CreateUserRequest_Email struct {
	Email string `protobuf:"bytes,1,opt,name=email,proto3,oneof"`
}

type CreateUserRequest_Phone struct {
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3,oneof"`
}

func (*CreateUserRequest_Email) isCreateUserRequest_Contact() {}

func (*CreateUserRequest_Phone) isCreateUserRequest_Contact() {}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_users_v1_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterContactRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Types that are valid to be assigned to ContactType:
	//
	//	*RegisterContactRequest_Phone
	//	*RegisterContactRequest_Email
	ContactType   isRegisterContactRequest_ContactType `protobuf_oneof:"contact_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterContactRequest) Reset() {
	*x = RegisterContactRequest{}
	mi := &file_users_v1_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterContactRequest) ProtoMessage() {}

func (x *RegisterContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterContactRequest.ProtoReflect.Descriptor instead.
func (*RegisterContactRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterContactRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterContactRequest) GetContactType() isRegisterContactRequest_ContactType {
	if x != nil {
		return x.ContactType
	}
	return nil
}

func (x *RegisterContactRequest) GetPhone() string {
	if x != nil {
		if x, ok := x.ContactType.(*RegisterContactRequest_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

func (x *RegisterContactRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.ContactType.(*RegisterContactRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

type isRegisterContactRequest_ContactType interface {
	isRegisterContactRequest_ContactType()
}

type RegisterContactRequest_Phone struct {
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3,oneof"`
}

type RegisterContactRequest_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

func (*RegisterContactRequest_Phone) isRegisterContactRequest_ContactType() {}

func (*RegisterContactRequest_Email) isRegisterContactRequest_ContactType() {}

type RegisterContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterContactResponse) Reset() {
	*x = RegisterContactResponse{}
	mi := &file_users_v1_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterContactResponse) ProtoMessage() {}

func (x *RegisterContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterContactResponse.ProtoReflect.Descriptor instead.
func (*RegisterContactResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{6}
}

type UpdateUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username        *string                `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	DisplayName     *string                `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	ProfileImageUrl *string                `protobuf:"bytes,6,opt,name=profile_image_url,json=profileImageUrl,proto3,oneof" json:"profile_image_url,omitempty"`
	Bio             *string                `protobuf:"bytes,7,opt,name=bio,proto3,oneof" json:"bio,omitempty"`
	BioStatus       *string                `protobuf:"bytes,8,opt,name=bio_status,json=bioStatus,proto3,oneof" json:"bio_status,omitempty"`
	AccountBadge    *AccountBadge          `protobuf:"varint,11,opt,name=account_badge,json=accountBadge,proto3,enum=users.v1.AccountBadge,oneof" json:"account_badge,omitempty"`
	FriendsCount    *uint32                `protobuf:"varint,12,opt,name=friends_count,json=friendsCount,proto3,oneof" json:"friends_count,omitempty"`
	FollowersCount  *uint32                `protobuf:"varint,13,opt,name=followers_count,json=followersCount,proto3,oneof" json:"followers_count,omitempty"`
	FollowingCount  *uint32                `protobuf:"varint,14,opt,name=following_count,json=followingCount,proto3,oneof" json:"following_count,omitempty"`
	PostsCount      *uint32                `protobuf:"varint,15,opt,name=posts_count,json=postsCount,proto3,oneof" json:"posts_count,omitempty"`
	BirthDate       *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=birth_date,json=birthDate,proto3,oneof" json:"birth_date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_users_v1_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateUserRequest) GetProfileImageUrl() string {
	if x != nil && x.ProfileImageUrl != nil {
		return *x.ProfileImageUrl
	}
	return ""
}

func (x *UpdateUserRequest) GetBio() string {
	if x != nil && x.Bio != nil {
		return *x.Bio
	}
	return ""
}

func (x *UpdateUserRequest) GetBioStatus() string {
	if x != nil && x.BioStatus != nil {
		return *x.BioStatus
	}
	return ""
}

func (x *UpdateUserRequest) GetAccountBadge() AccountBadge {
	if x != nil && x.AccountBadge != nil {
		return *x.AccountBadge
	}
	return AccountBadge_UNVERIFIED
}

func (x *UpdateUserRequest) GetFriendsCount() uint32 {
	if x != nil && x.FriendsCount != nil {
		return *x.FriendsCount
	}
	return 0
}

func (x *UpdateUserRequest) GetFollowersCount() uint32 {
	if x != nil && x.FollowersCount != nil {
		return *x.FollowersCount
	}
	return 0
}

func (x *UpdateUserRequest) GetFollowingCount() uint32 {
	if x != nil && x.FollowingCount != nil {
		return *x.FollowingCount
	}
	return 0
}

func (x *UpdateUserRequest) GetPostsCount() uint32 {
	if x != nil && x.PostsCount != nil {
		return *x.PostsCount
	}
	return 0
}

func (x *UpdateUserRequest) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_users_v1_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{8}
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_users_v1_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_users_v1_users_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{10}
}

type RestoreUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreUserRequest) Reset() {
	*x = RestoreUserRequest{}
	mi := &file_users_v1_users_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreUserRequest) ProtoMessage() {}

func (x *RestoreUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreUserRequest.ProtoReflect.Descriptor instead.
func (*RestoreUserRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{11}
}

func (x *RestoreUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RestoreUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreUserResponse) Reset() {
	*x = RestoreUserResponse{}
	mi := &file_users_v1_users_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreUserResponse) ProtoMessage() {}

func (x *RestoreUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreUserResponse.ProtoReflect.Descriptor instead.
func (*RestoreUserResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{12}
}

type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Lookup:
	//
	//	*GetUserRequest_Id
	//	*GetUserRequest_Username
	//	*GetUserRequest_Email
	//	*GetUserRequest_Phone
	Lookup        isGetUserRequest_Lookup `protobuf_oneof:"lookup"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_users_v1_users_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserRequest) GetLookup() isGetUserRequest_Lookup {
	if x != nil {
		return x.Lookup
	}
	return nil
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		if x, ok := x.Lookup.(*GetUserRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *GetUserRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.Lookup.(*GetUserRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *GetUserRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Lookup.(*GetUserRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *GetUserRequest) GetPhone() string {
	if x != nil {
		if x, ok := x.Lookup.(*GetUserRequest_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

type isGetUserRequest_Lookup interface {
	isGetUserRequest_Lookup()
}

type GetUserRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type GetUserRequest_Username struct {
	Username string `protobuf:"bytes,2,opt,name=username,proto3,oneof"`
}

type GetUserRequest_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

type GetUserRequest_Phone struct {
	Phone string `protobuf:"bytes,4,opt,name=phone,proto3,oneof"`
}

func (*GetUserRequest_Id) isGetUserRequest_Lookup() {}

func (*GetUserRequest_Username) isGetUserRequest_Lookup() {}

func (*GetUserRequest_Email) isGetUserRequest_Lookup() {}

func (*GetUserRequest_Phone) isGetUserRequest_Lookup() {}

type GetUserResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	User            *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	PrivacySettings *PrivacySettings       `protobuf:"bytes,2,opt,name=privacy_settings,json=privacySettings,proto3" json:"privacy_settings,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_users_v1_users_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserResponse) GetPrivacySettings() *PrivacySettings {
	if x != nil {
		return x.PrivacySettings
	}
	return nil
}

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_users_v1_users_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{15}
}

func (x *GetUsersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_users_v1_users_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{16}
}

func (x *GetUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetUserSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSummaryRequest) Reset() {
	*x = GetUserSummaryRequest{}
	mi := &file_users_v1_users_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSummaryRequest) ProtoMessage() {}

func (x *GetUserSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetUserSummaryRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserSummaryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserSummary           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSummaryResponse) Reset() {
	*x = GetUserSummaryResponse{}
	mi := &file_users_v1_users_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSummaryResponse) ProtoMessage() {}

func (x *GetUserSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetUserSummaryResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserSummaryResponse) GetUser() *UserSummary {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUsersSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersSummaryRequest) Reset() {
	*x = GetUsersSummaryRequest{}
	mi := &file_users_v1_users_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersSummaryRequest) ProtoMessage() {}

func (x *GetUsersSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetUsersSummaryRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{19}
}

func (x *GetUsersSummaryRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetUsersSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserSummary         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersSummaryResponse) Reset() {
	*x = GetUsersSummaryResponse{}
	mi := &file_users_v1_users_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersSummaryResponse) ProtoMessage() {}

func (x *GetUsersSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetUsersSummaryResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{20}
}

func (x *GetUsersSummaryResponse) GetUsers() []*UserSummary {
	if x != nil {
		return x.Users
	}
	return nil
}

type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_users_v1_users_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{21}
}

func (x *SearchUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsersRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchUsersRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserSummary         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResponse) Reset() {
	*x = SearchUsersResponse{}
	mi := &file_users_v1_users_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResponse) ProtoMessage() {}

func (x *SearchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{22}
}

func (x *SearchUsersResponse) GetUsers() []*UserSummary {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SearchUsersResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type UserExistsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Lookup:
	//
	//	*UserExistsRequest_Id
	//	*UserExistsRequest_Username
	//	*UserExistsRequest_Email
	//	*UserExistsRequest_Phone
	Lookup        isUserExistsRequest_Lookup `protobuf_oneof:"lookup"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserExistsRequest) Reset() {
	*x = UserExistsRequest{}
	mi := &file_users_v1_users_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExistsRequest) ProtoMessage() {}

func (x *UserExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExistsRequest.ProtoReflect.Descriptor instead.
func (*UserExistsRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{23}
}

func (x *UserExistsRequest) GetLookup() isUserExistsRequest_Lookup {
	if x != nil {
		return x.Lookup
	}
	return nil
}

func (x *UserExistsRequest) GetId() string {
	if x != nil {
		if x, ok := x.Lookup.(*UserExistsRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *UserExistsRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.Lookup.(*UserExistsRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *UserExistsRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.Lookup.(*UserExistsRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *UserExistsRequest) GetPhone() string {
	if x != nil {
		if x, ok := x.Lookup.(*UserExistsRequest_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

type isUserExistsRequest_Lookup interface {
	isUserExistsRequest_Lookup()
}

type UserExistsRequest_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type UserExistsRequest_Username struct {
	Username string `protobuf:"bytes,2,opt,name=username,proto3,oneof"`
}

type UserExistsRequest_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

type UserExistsRequest_Phone struct {
	Phone string `protobuf:"bytes,4,opt,name=phone,proto3,oneof"`
}

func (*UserExistsRequest_Id) isUserExistsRequest_Lookup() {}

func (*UserExistsRequest_Username) isUserExistsRequest_Lookup() {}

func (*UserExistsRequest_Email) isUserExistsRequest_Lookup() {}

func (*UserExistsRequest_Phone) isUserExistsRequest_Lookup() {}

type UserExistence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserExistence) Reset() {
	*x = UserExistence{}
	mi := &file_users_v1_users_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserExistence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExistence) ProtoMessage() {}

func (x *UserExistence) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExistence.ProtoReflect.Descriptor instead.
func (*UserExistence) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{24}
}

func (x *UserExistence) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserExistence) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type UserExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *UserExistence         `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserExistsResponse) Reset() {
	*x = UserExistsResponse{}
	mi := &file_users_v1_users_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExistsResponse) ProtoMessage() {}

func (x *UserExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExistsResponse.ProtoReflect.Descriptor instead.
func (*UserExistsResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{25}
}

func (x *UserExistsResponse) GetResponse() *UserExistence {
	if x != nil {
		return x.Response
	}
	return nil
}

type UsersExistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersExistRequest) Reset() {
	*x = UsersExistRequest{}
	mi := &file_users_v1_users_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersExistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersExistRequest) ProtoMessage() {}

func (x *UsersExistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersExistRequest.ProtoReflect.Descriptor instead.
func (*UsersExistRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{26}
}

func (x *UsersExistRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type UsersExistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserExistence       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersExistResponse) Reset() {
	*x = UsersExistResponse{}
	mi := &file_users_v1_users_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersExistResponse) ProtoMessage() {}

func (x *UsersExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersExistResponse.ProtoReflect.Descriptor instead.
func (*UsersExistResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{27}
}

func (x *UsersExistResponse) GetUsers() []*UserExistence {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetPrivacySettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivacySettingsRequest) Reset() {
	*x = GetPrivacySettingsRequest{}
	mi := &file_users_v1_users_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivacySettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivacySettingsRequest) ProtoMessage() {}

func (x *GetPrivacySettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivacySettingsRequest.ProtoReflect.Descriptor instead.
func (*GetPrivacySettingsRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{28}
}

func (x *GetPrivacySettingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPrivacySettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *PrivacySettings       `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivacySettingsResponse) Reset() {
	*x = GetPrivacySettingsResponse{}
	mi := &file_users_v1_users_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivacySettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivacySettingsResponse) ProtoMessage() {}

func (x *GetPrivacySettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivacySettingsResponse.ProtoReflect.Descriptor instead.
func (*GetPrivacySettingsResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{29}
}

func (x *GetPrivacySettingsResponse) GetSettings() *PrivacySettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdatePrivacySettingsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AvatarVisibility    *Visibility            `protobuf:"varint,2,opt,name=avatar_visibility,json=avatarVisibility,proto3,enum=users.v1.Visibility,oneof" json:"avatar_visibility,omitempty"`
	PhoneVisibility     *Visibility            `protobuf:"varint,3,opt,name=phone_visibility,json=phoneVisibility,proto3,enum=users.v1.Visibility,oneof" json:"phone_visibility,omitempty"`
	EmailVisibility     *Visibility            `protobuf:"varint,4,opt,name=email_visibility,json=emailVisibility,proto3,enum=users.v1.Visibility,oneof" json:"email_visibility,omitempty"`
	LastSeenVisibility  *Visibility            `protobuf:"varint,5,opt,name=last_seen_visibility,json=lastSeenVisibility,proto3,enum=users.v1.Visibility,oneof" json:"last_seen_visibility,omitempty"`
	ReadReceiptsEnabled *bool                  `protobuf:"varint,6,opt,name=read_receipts_enabled,json=readReceiptsEnabled,proto3,oneof" json:"read_receipts_enabled,omitempty"`
	FindByUsername      *bool                  `protobuf:"varint,7,opt,name=find_by_username,json=findByUsername,proto3,oneof" json:"find_by_username,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdatePrivacySettingsRequest) Reset() {
	*x = UpdatePrivacySettingsRequest{}
	mi := &file_users_v1_users_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePrivacySettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePrivacySettingsRequest) ProtoMessage() {}

func (x *UpdatePrivacySettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePrivacySettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdatePrivacySettingsRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{30}
}

func (x *UpdatePrivacySettingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePrivacySettingsRequest) GetAvatarVisibility() Visibility {
	if x != nil && x.AvatarVisibility != nil {
		return *x.AvatarVisibility
	}
	return Visibility_EVERYONE
}

func (x *UpdatePrivacySettingsRequest) GetPhoneVisibility() Visibility {
	if x != nil && x.PhoneVisibility != nil {
		return *x.PhoneVisibility
	}
	return Visibility_EVERYONE
}

func (x *UpdatePrivacySettingsRequest) GetEmailVisibility() Visibility {
	if x != nil && x.EmailVisibility != nil {
		return *x.EmailVisibility
	}
	return Visibility_EVERYONE
}

func (x *UpdatePrivacySettingsRequest) GetLastSeenVisibility() Visibility {
	if x != nil && x.LastSeenVisibility != nil {
		return *x.LastSeenVisibility
	}
	return Visibility_EVERYONE
}

func (x *UpdatePrivacySettingsRequest) GetReadReceiptsEnabled() bool {
	if x != nil && x.ReadReceiptsEnabled != nil {
		return *x.ReadReceiptsEnabled
	}
	return false
}

func (x *UpdatePrivacySettingsRequest) GetFindByUsername() bool {
	if x != nil && x.FindByUsername != nil {
		return *x.FindByUsername
	}
	return false
}

type UpdatePrivacySettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePrivacySettingsResponse) Reset() {
	*x = UpdatePrivacySettingsResponse{}
	mi := &file_users_v1_users_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePrivacySettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePrivacySettingsResponse) ProtoMessage() {}

func (x *UpdatePrivacySettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePrivacySettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdatePrivacySettingsResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{31}
}

var File_users_v1_users_proto protoreflect.FileDescriptor

const file_users_v1_users_proto_rawDesc = "" +
	"\n" +
	"\x14users/v1/users.proto\x12\busers.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xe4\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12*\n" +
	"\x11profile_image_url\x18\x06 \x01(\tR\x0fprofileImageUrl\x12\x10\n" +
	"\x03bio\x18\a \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"bio_status\x18\b \x01(\tR\tbioStatus\x12;\n" +
	"\raccount_badge\x18\t \x01(\x0e2\x16.users.v1.AccountBadgeR\faccountBadge\x12#\n" +
	"\rfriends_count\x18\n" +
	" \x01(\rR\ffriendsCount\x12'\n" +
	"\x0ffollowers_count\x18\v \x01(\rR\x0efollowersCount\x12'\n" +
	"\x0ffollowing_count\x18\f \x01(\rR\x0efollowingCount\x12\x1f\n" +
	"\vposts_count\x18\r \x01(\rR\n" +
	"postsCount\x129\n" +
	"\n" +
	"birth_date\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tbirthDate\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe8\x01\n" +
	"\vUserSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12*\n" +
	"\x11profile_image_url\x18\x05 \x01(\tR\x0fprofileImageUrl\x12;\n" +
	"\raccount_badge\x18\x06 \x01(\x0e2\x16.users.v1.AccountBadgeR\faccountBadge\"\xfc\x02\n" +
	"\x0fPrivacySettings\x12A\n" +
	"\x11avatar_visibility\x18\x01 \x01(\x0e2\x14.users.v1.VisibilityR\x10avatarVisibility\x12?\n" +
	"\x10phone_visibility\x18\x02 \x01(\x0e2\x14.users.v1.VisibilityR\x0fphoneVisibility\x12?\n" +
	"\x10email_visibility\x18\x03 \x01(\x0e2\x14.users.v1.VisibilityR\x0femailVisibility\x12F\n" +
	"\x14last_seen_visibility\x18\x04 \x01(\x0e2\x14.users.v1.VisibilityR\x12lastSeenVisibility\x122\n" +
	"\x15read_receipts_enabled\x18\x05 \x01(\bR\x13readReceiptsEnabled\x12(\n" +
	"\x10find_by_username\x18\x06 \x01(\bR\x0efindByUsername\"N\n" +
	"\x11CreateUserRequest\x12\x16\n" +
	"\x05email\x18\x01 \x01(\tH\x00R\x05email\x12\x16\n" +
	"\x05phone\x18\x02 \x01(\tH\x00R\x05phoneB\t\n" +
	"\acontact\"8\n" +
	"\x12CreateUserResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.users.v1.UserR\x04user\"q\n" +
	"\x16RegisterContactRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x05phone\x18\x02 \x01(\tH\x00R\x05phone\x12\x16\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05emailB\x0e\n" +
	"\fcontact_type\"\x19\n" +
	"\x17RegisterContactResponse\"\xbc\x05\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x88\x01\x01\x12&\n" +
	"\fdisplay_name\x18\x03 \x01(\tH\x01R\vdisplayName\x88\x01\x01\x12/\n" +
	"\x11profile_image_url\x18\x06 \x01(\tH\x02R\x0fprofileImageUrl\x88\x01\x01\x12\x15\n" +
	"\x03bio\x18\a \x01(\tH\x03R\x03bio\x88\x01\x01\x12\"\n" +
	"\n" +
	"bio_status\x18\b \x01(\tH\x04R\tbioStatus\x88\x01\x01\x12@\n" +
	"\raccount_badge\x18\v \x01(\x0e2\x16.users.v1.AccountBadgeH\x05R\faccountBadge\x88\x01\x01\x12(\n" +
	"\rfriends_count\x18\f \x01(\rH\x06R\ffriendsCount\x88\x01\x01\x12,\n" +
	"\x0ffollowers_count\x18\r \x01(\rH\aR\x0efollowersCount\x88\x01\x01\x12,\n" +
	"\x0ffollowing_count\x18\x0e \x01(\rH\bR\x0efollowingCount\x88\x01\x01\x12$\n" +
	"\vposts_count\x18\x0f \x01(\rH\tR\n" +
	"postsCount\x88\x01\x01\x12>\n" +
	"\n" +
	"birth_date\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampH\n" +
	"R\tbirthDate\x88\x01\x01B\v\n" +
	"\t_usernameB\x0f\n" +
	"\r_display_nameB\x14\n" +
	"\x12_profile_image_urlB\x06\n" +
	"\x04_bioB\r\n" +
	"\v_bio_statusB\x10\n" +
	"\x0e_account_badgeB\x10\n" +
	"\x0e_friends_countB\x12\n" +
	"\x10_followers_countB\x12\n" +
	"\x10_following_countB\x0e\n" +
	"\f_posts_countB\r\n" +
	"\v_birth_date\"\x14\n" +
	"\x12UpdateUserResponse\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteUserResponse\"$\n" +
	"\x12RestoreUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13RestoreUserResponse\"z\n" +
	"\x0eGetUserRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x1c\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x12\x16\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05email\x12\x16\n" +
	"\x05phone\x18\x04 \x01(\tH\x00R\x05phoneB\b\n" +
	"\x06lookup\"{\n" +
	"\x0fGetUserResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.users.v1.UserR\x04user\x12D\n" +
	"\x10privacy_settings\x18\x02 \x01(\v2\x19.users.v1.PrivacySettingsR\x0fprivacySettings\",\n" +
	"\x0fGetUsersRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"8\n" +
	"\x10GetUsersResponse\x12$\n" +
	"\x05users\x18\x01 \x03(\v2\x0e.users.v1.UserR\x05users\"'\n" +
	"\x15GetUserSummaryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x16GetUserSummaryResponse\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.users.v1.UserSummaryR\x04user\"3\n" +
	"\x16GetUsersSummaryRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"F\n" +
	"\x17GetUsersSummaryResponse\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.users.v1.UserSummaryR\x05users\"[\n" +
	"\x12SearchUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\"]\n" +
	"\x13SearchUsersResponse\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.users.v1.UserSummaryR\x05users\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"}\n" +
	"\x11UserExistsRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x1c\n" +
	"\busername\x18\x02 \x01(\tH\x00R\busername\x12\x16\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05email\x12\x16\n" +
	"\x05phone\x18\x04 \x01(\tH\x00R\x05phoneB\b\n" +
	"\x06lookup\"@\n" +
	"\rUserExistence\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"I\n" +
	"\x12UserExistsResponse\x123\n" +
	"\bresponse\x18\x01 \x01(\v2\x17.users.v1.UserExistenceR\bresponse\".\n" +
	"\x11UsersExistRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"C\n" +
	"\x12UsersExistResponse\x12-\n" +
	"\x05users\x18\x01 \x03(\v2\x17.users.v1.UserExistenceR\x05users\"4\n" +
	"\x19GetPrivacySettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"S\n" +
	"\x1aGetPrivacySettingsResponse\x125\n" +
	"\bsettings\x18\x01 \x01(\v2\x19.users.v1.PrivacySettingsR\bsettings\"\xc8\x04\n" +
	"\x1cUpdatePrivacySettingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12F\n" +
	"\x11avatar_visibility\x18\x02 \x01(\x0e2\x14.users.v1.VisibilityH\x00R\x10avatarVisibility\x88\x01\x01\x12D\n" +
	"\x10phone_visibility\x18\x03 \x01(\x0e2\x14.users.v1.VisibilityH\x01R\x0fphoneVisibility\x88\x01\x01\x12D\n" +
	"\x10email_visibility\x18\x04 \x01(\x0e2\x14.users.v1.VisibilityH\x02R\x0femailVisibility\x88\x01\x01\x12K\n" +
	"\x14last_seen_visibility\x18\x05 \x01(\x0e2\x14.users.v1.VisibilityH\x03R\x12lastSeenVisibility\x88\x01\x01\x127\n" +
	"\x15read_receipts_enabled\x18\x06 \x01(\bH\x04R\x13readReceiptsEnabled\x88\x01\x01\x12-\n" +
	"\x10find_by_username\x18\a \x01(\bH\x05R\x0efindByUsername\x88\x01\x01B\x14\n" +
	"\x12_avatar_visibilityB\x13\n" +
	"\x11_phone_visibilityB\x13\n" +
	"\x11_email_visibilityB\x17\n" +
	"\x15_last_seen_visibilityB\x18\n" +
	"\x16_read_receipts_enabledB\x13\n" +
	"\x11_find_by_username\"\x1f\n" +
	"\x1dUpdatePrivacySettingsResponse*A\n" +
	"\n" +
	"Visibility\x12\f\n" +
	"\bEVERYONE\x10\x00\x12\v\n" +
	"\aFRIENDS\x10\x01\x12\f\n" +
	"\bCONTACTS\x10\x02\x12\n" +
	"\n" +
	"\x06NOBODY\x10\x03*P\n" +
	"\fAccountBadge\x12\x0e\n" +
	"\n" +
	"UNVERIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"BLUE_BADGE\x10\x01\x12\x0e\n" +
	"\n" +
	"GOLD_BADGE\x10\x02\x12\x10\n" +
	"\fSILVER_BADGE\x10\x032\xe6\b\n" +
	"\fUsersService\x12G\n" +
	"\n" +
	"CreateUser\x12\x1b.users.v1.CreateUserRequest\x1a\x1c.users.v1.CreateUserResponse\x12V\n" +
	"\x0fRegisterContact\x12 .users.v1.RegisterContactRequest\x1a!.users.v1.RegisterContactResponse\x12G\n" +
	"\n" +
	"UpdateUser\x12\x1b.users.v1.UpdateUserRequest\x1a\x1c.users.v1.UpdateUserResponse\x12G\n" +
	"\n" +
	"DeleteUser\x12\x1b.users.v1.DeleteUserRequest\x1a\x1c.users.v1.DeleteUserResponse\x12J\n" +
	"\vRestoreUser\x12\x1c.users.v1.RestoreUserRequest\x1a\x1d.users.v1.RestoreUserResponse\x12>\n" +
	"\aGetUser\x12\x18.users.v1.GetUserRequest\x1a\x19.users.v1.GetUserResponse\x12A\n" +
	"\bGetUsers\x12\x19.users.v1.GetUsersRequest\x1a\x1a.users.v1.GetUsersResponse\x12S\n" +
	"\x0eGetUserSummary\x12\x1f.users.v1.GetUserSummaryRequest\x1a .users.v1.GetUserSummaryResponse\x12V\n" +
	"\x0fGetUsersSummary\x12 .users.v1.GetUsersSummaryRequest\x1a!.users.v1.GetUsersSummaryResponse\x12J\n" +
	"\vSearchUsers\x12\x1c.users.v1.SearchUsersRequest\x1a\x1d.users.v1.SearchUsersResponse\x12G\n" +
	"\n" +
	"UserExists\x12\x1b.users.v1.UserExistsRequest\x1a\x1c.users.v1.UserExistsResponse\x12G\n" +
	"\n" +
	"UsersExist\x12\x1b.users.v1.UsersExistRequest\x1a\x1c.users.v1.UsersExistResponse\x12_\n" +
	"\x12GetPrivacySettings\x12#.users.v1.GetPrivacySettingsRequest\x1a$.users.v1.GetPrivacySettingsResponse\x12h\n" +
	"\x15UpdatePrivacySettings\x12&.users.v1.UpdatePrivacySettingsRequest\x1a'.users.v1.UpdatePrivacySettingsResponseB\x1aZ\x18shared/proto/users;usersb\x06proto3"

var (
	file_users_v1_users_proto_rawDescOnce sync.Once
	file_users_v1_users_proto_rawDescData []byte
)

func file_users_v1_users_proto_rawDescGZIP() []byte {
	file_users_v1_users_proto_rawDescOnce.Do(func() {
		file_users_v1_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_v1_users_proto_rawDesc), len(file_users_v1_users_proto_rawDesc)))
	})
	return file_users_v1_users_proto_rawDescData
}

var file_users_v1_users_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_users_v1_users_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_users_v1_users_proto_goTypes = []any{
	(Visibility)(0),                       // 0: users.v1.Visibility
	(AccountBadge)(0),                     // 1: users.v1.AccountBadge
	(*User)(nil),                          // 2: users.v1.User
	(*UserSummary)(nil),                   // 3: users.v1.UserSummary
	(*PrivacySettings)(nil),               // 4: users.v1.PrivacySettings
	(*CreateUserRequest)(nil),             // 5: users.v1.CreateUserRequest
	(*CreateUserResponse)(nil),            // 6: users.v1.CreateUserResponse
	(*RegisterContactRequest)(nil),        // 7: users.v1.RegisterContactRequest
	(*RegisterContactResponse)(nil),       // 8: users.v1.RegisterContactResponse
	(*UpdateUserRequest)(nil),             // 9: users.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),            // 10: users.v1.UpdateUserResponse
	(*DeleteUserRequest)(nil),             // 11: users.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),            // 12: users.v1.DeleteUserResponse
	(*RestoreUserRequest)(nil),            // 13: users.v1.RestoreUserRequest
	(*RestoreUserResponse)(nil),           // 14: users.v1.RestoreUserResponse
	(*GetUserRequest)(nil),                // 15: users.v1.GetUserRequest
	(*GetUserResponse)(nil),               // 16: users.v1.GetUserResponse
	(*GetUsersRequest)(nil),               // 17: users.v1.GetUsersRequest
	(*GetUsersResponse)(nil),              // 18: users.v1.GetUsersResponse
	(*GetUserSummaryRequest)(nil),         // 19: users.v1.GetUserSummaryRequest
	(*GetUserSummaryResponse)(nil),        // 20: users.v1.GetUserSummaryResponse
	(*GetUsersSummaryRequest)(nil),        // 21: users.v1.GetUsersSummaryRequest
	(*GetUsersSummaryResponse)(nil),       // 22: users.v1.GetUsersSummaryResponse
	(*SearchUsersRequest)(nil),            // 23: users.v1.SearchUsersRequest
	(*SearchUsersResponse)(nil),           // 24: users.v1.SearchUsersResponse
	(*UserExistsRequest)(nil),             // 25: users.v1.UserExistsRequest
	(*UserExistence)(nil),                 // 26: users.v1.UserExistence
	(*UserExistsResponse)(nil),            // 27: users.v1.UserExistsResponse
	(*UsersExistRequest)(nil),             // 28: users.v1.UsersExistRequest
	(*UsersExistResponse)(nil),            // 29: users.v1.UsersExistResponse
	(*GetPrivacySettingsRequest)(nil),     // 30: users.v1.GetPrivacySettingsRequest
	(*GetPrivacySettingsResponse)(nil),    // 31: users.v1.GetPrivacySettingsResponse
	(*UpdatePrivacySettingsRequest)(nil),  // 32: users.v1.UpdatePrivacySettingsRequest
	(*UpdatePrivacySettingsResponse)(nil), // 33: users.v1.UpdatePrivacySettingsResponse
	(*timestamppb.Timestamp)(nil),         // 34: google.protobuf.Timestamp
}
var file_users_v1_users_proto_depIdxs = []int32{
	1,  // 0: users.v1.User.account_badge:type_name -> users.v1.AccountBadge
	34, // 1: users.v1.User.birth_date:type_name -> google.protobuf.Timestamp
	34, // 2: users.v1.User.created_at:type_name -> google.protobuf.Timestamp
	34, // 3: users.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: users.v1.UserSummary.account_badge:type_name -> users.v1.AccountBadge
	0,  // 5: users.v1.PrivacySettings.avatar_visibility:type_name -> users.v1.Visibility
	0,  // 6: users.v1.PrivacySettings.phone_visibility:type_name -> users.v1.Visibility
	0,  // 7: users.v1.PrivacySettings.email_visibility:type_name -> users.v1.Visibility
	0,  // 8: users.v1.PrivacySettings.last_seen_visibility:type_name -> users.v1.Visibility
	2,  // 9: users.v1.CreateUserResponse.user:type_name -> users.v1.User
	1,  // 10: users.v1.UpdateUserRequest.account_badge:type_name -> users.v1.AccountBadge
	34, // 11: users.v1.UpdateUserRequest.birth_date:type_name -> google.protobuf.Timestamp
	2,  // 12: users.v1.GetUserResponse.user:type_name -> users.v1.User
	4,  // 13: users.v1.GetUserResponse.privacy_settings:type_name -> users.v1.PrivacySettings
	2,  // 14: users.v1.GetUsersResponse.users:type_name -> users.v1.User
	3,  // 15: users.v1.GetUserSummaryResponse.user:type_name -> users.v1.UserSummary
	3,  // 16: users.v1.GetUsersSummaryResponse.users:type_name -> users.v1.UserSummary
	3,  // 17: users.v1.SearchUsersResponse.users:type_name -> users.v1.UserSummary
	26, // 18: users.v1.UserExistsResponse.response:type_name -> users.v1.UserExistence
	26, // 19: users.v1.UsersExistResponse.users:type_name -> users.v1.UserExistence
	4,  // 20: users.v1.GetPrivacySettingsResponse.settings:type_name -> users.v1.PrivacySettings
	0,  // 21: users.v1.UpdatePrivacySettingsRequest.avatar_visibility:type_name -> users.v1.Visibility
	0,  // 22: users.v1.UpdatePrivacySettingsRequest.phone_visibility:type_name -> users.v1.Visibility
	0,  // 23: users.v1.UpdatePrivacySettingsRequest.email_visibility:type_name -> users.v1.Visibility
	0,  // 24: users.v1.UpdatePrivacySettingsRequest.last_seen_visibility:type_name -> users.v1.Visibility
	5,  // 25: users.v1.UsersService.CreateUser:input_type -> users.v1.CreateUserRequest
	7,  // 26: users.v1.UsersService.RegisterContact:input_type -> users.v1.RegisterContactRequest
	9,  // 27: users.v1.UsersService.UpdateUser:input_type -> users.v1.UpdateUserRequest
	11, // 28: users.v1.UsersService.DeleteUser:input_type -> users.v1.DeleteUserRequest
	13, // 29: users.v1.UsersService.RestoreUser:input_type -> users.v1.RestoreUserRequest
	15, // 30: users.v1.UsersService.GetUser:input_type -> users.v1.GetUserRequest
	17, // 31: users.v1.UsersService.GetUsers:input_type -> users.v1.GetUsersRequest
	19, // 32: users.v1.UsersService.GetUserSummary:input_type -> users.v1.GetUserSummaryRequest
	21, // 33: users.v1.UsersService.GetUsersSummary:input_type -> users.v1.GetUsersSummaryRequest
	23, // 34: users.v1.UsersService.SearchUsers:input_type -> users.v1.SearchUsersRequest
	25, // 35: users.v1.UsersService.UserExists:input_type -> users.v1.UserExistsRequest
	28, // 36: users.v1.UsersService.UsersExist:input_type -> users.v1.UsersExistRequest
	30, // 37: users.v1.UsersService.GetPrivacySettings:input_type -> users.v1.GetPrivacySettingsRequest
	32, // 38: users.v1.UsersService.UpdatePrivacySettings:input_type -> users.v1.UpdatePrivacySettingsRequest
	6,  // 39: users.v1.UsersService.CreateUser:output_type -> users.v1.CreateUserResponse
	8,  // 40: users.v1.UsersService.RegisterContact:output_type -> users.v1.RegisterContactResponse
	10, // 41: users.v1.UsersService.UpdateUser:output_type -> users.v1.UpdateUserResponse
	12, // 42: users.v1.UsersService.DeleteUser:output_type -> users.v1.DeleteUserResponse
	14, // 43: users.v1.UsersService.RestoreUser:output_type -> users.v1.RestoreUserResponse
	16, // 44: users.v1.UsersService.GetUser:output_type -> users.v1.GetUserResponse
	18, // 45: users.v1.UsersService.GetUsers:output_type -> users.v1.GetUsersResponse
	20, // 46: users.v1.UsersService.GetUserSummary:output_type -> users.v1.GetUserSummaryResponse
	22, // 47: users.v1.UsersService.GetUsersSummary:output_type -> users.v1.GetUsersSummaryResponse
	24, // 48: users.v1.UsersService.SearchUsers:output_type -> users.v1.SearchUsersResponse
	27, // 49: users.v1.UsersService.UserExists:output_type -> users.v1.UserExistsResponse
	29, // 50: users.v1.UsersService.UsersExist:output_type -> users.v1.UsersExistResponse
	31, // 51: users.v1.UsersService.GetPrivacySettings:output_type -> users.v1.GetPrivacySettingsResponse
	33, // 52: users.v1.UsersService.UpdatePrivacySettings:output_type -> users.v1.UpdatePrivacySettingsResponse
	39, // [39:53] is the sub-list for method output_type
	25, // [25:39] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_users_v1_users_proto_init() }
func file_users_v1_users_proto_init() {
	if File_users_v1_users_proto != nil {
		return
	}
	file_users_v1_users_proto_msgTypes[3].OneofWrappers = []any{
		(*CreateUserRequest_Email)(nil),
		(*CreateUserRequest_Phone)(nil),
	}
	file_users_v1_users_proto_msgTypes[5].OneofWrappers = []any{
		(*RegisterContactRequest_Phone)(nil),
		(*RegisterContactRequest_Email)(nil),
	}
	file_users_v1_users_proto_msgTypes[7].OneofWrappers = []any{}
	file_users_v1_users_proto_msgTypes[13].OneofWrappers = []any{
		(*GetUserRequest_Id)(nil),
		(*GetUserRequest_Username)(nil),
		(*GetUserRequest_Email)(nil),
		(*GetUserRequest_Phone)(nil),
	}
	file_users_v1_users_proto_msgTypes[23].OneofWrappers = []any{
		(*UserExistsRequest_Id)(nil),
		(*UserExistsRequest_Username)(nil),
		(*UserExistsRequest_Email)(nil),
		(*UserExistsRequest_Phone)(nil),
	}
	file_users_v1_users_proto_msgTypes[30].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_v1_users_proto_rawDesc), len(file_users_v1_users_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_v1_users_proto_goTypes,
		DependencyIndexes: file_users_v1_users_proto_depIdxs,
		EnumInfos:         file_users_v1_users_proto_enumTypes,
		MessageInfos:      file_users_v1_users_proto_msgTypes,
	}.Build()
	File_users_v1_users_proto = out.File
	file_users_v1_users_proto_goTypes = nil
	file_users_v1_users_proto_depIdxs = nil
}
